title:  <img src="LOGO 3.png" alt="drawing" width="20"/> Physical Data Research Group   
description: International group of physicists working on Data Science.
show_downloads: false
google_analytics:
theme: jekyll-theme-dinky
